apiVersion: batch/v1
kind: Job
metadata:
  name: k6-loadtest
  namespace: flash-sale
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:0.44.0
          command: ["k6", "run", "/scripts/test.js"]
          volumeMounts:
            - name: script
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: script
          configMap:
            name: k6-script
