apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  namepsace: flash-sale
spec:
  selector:
    matchLabels:
      app: order-service
  namespaceSelector:
    matchNames:
      - ecommerce
    endpoints:
      - port: metrics
        path: /metrics
        interval: 10s
